### ISSUE TITLE
Crash on Exit v1.4.1

### ISSUE THREAD

**Issue by EXO5KELETON** [blawar/tinleaf#16]
When you quit the app via EXIT option you get a black screen for around 1/2 seconds then you get The software was closed because an error occurred.

Thanks for your work

**Comment by blawar** [comment]
It is being investigated, thank you.

**Comment by LiloBzH** [comment]
Same on 1.4.3 (SX OS)

**Comment by EXO5KELETON** [comment]
Still Crashes on exit on 1.4.3 atmosphere 0.15.0 and Horizon 10.2.0

**Comment by blawar** [comment]
fixed
