### ISSUE TITLE
Issue compiling

### ISSUE THREAD

**Issue by sevenpastzeero** [blawar/tinleaf#25]
Hello,
I get this error at the end of the compiling process:

`usb_util.cpp
util.cpp
es.c
ns_ext.c
debug.c
usb_comms_tinleaf.c
linking tinleaf.elf
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(usbhsfs_manager.o): in function 'usbHsFsInitialize':
H:/libusbhsfs/source/usbhsfs_manager.c:100: undefined reference to 'ext4_dmask_set'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(usbhsfs_mount.o): in function 'usbHsFsMountInspectExtSuperBlock':
H:/libusbhsfs/source/usbhsfs_mount.c:608: undefined reference to 'ext4_sb_check'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: H:/libusbhsfs/source/usbhsfs_mount.c:608: undefined reference to 'ext4_sb_check'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext.o): in function 'ext_mount':
H:/libusbhsfs/source/lwext4/ext.c:43: undefined reference to 'ext4_device_register'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: H:/libusbhsfs/source/lwext4/ext.c:56: undefined reference to 'ext4_mount'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: H:/libusbhsfs/source/lwext4/ext.c:68: undefined reference to 'ext4_recover'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: H:/libusbhsfs/source/lwext4/ext.c:75: undefined reference to 'ext4_journal_start'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: H:/libusbhsfs/source/lwext4/ext.c:89: undefined reference to 'ext4_umount'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: H:/libusbhsfs/source/lwext4/ext.c:91: undefined reference to 'ext4_device_unregister'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: H:/libusbhsfs/source/lwext4/ext.c:43: undefined reference to 'ext4_device_register'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext.o): in function 'ext_umount':
H:/libusbhsfs/source/lwext4/ext.c:108: undefined reference to 'ext4_journal_stop'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: H:/libusbhsfs/source/lwext4/ext.c:112: undefined reference to 'ext4_umount'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: H:/libusbhsfs/source/lwext4/ext.c:117: undefined reference to 'ext4_device_unregister'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext_dev.o): in function 'extdev_utimes':
H:/libusbhsfs/source/lwext4/ext_dev.c:761: undefined reference to 'ext4_atime_set'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: H:/libusbhsfs/source/lwext4/ext_dev.c:765: undefined reference to 'ext4_mtime_set'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext_dev.o): in function 'extdev_chmod':
H:/libusbhsfs/source/lwext4/ext_dev.c:664: undefined reference to 'ext4_mode_set'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext_dev.o): in function 'extdev_ftruncate':
H:/libusbhsfs/source/lwext4/ext_dev.c:634: undefined reference to 'ext4_ftruncate'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext_dev.o): in function 'extdev_statvfs':
H:/libusbhsfs/source/lwext4/ext_dev.c:597: undefined reference to 'ext4_mount_point_stats'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext_dev.o): in function 'extdev_fstat':
H:/libusbhsfs/source/lwext4/ext_dev.c:269: undefined reference to 'ext4_fs_get_inode_ref'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: H:/libusbhsfs/source/lwext4/ext_dev.c:276: undefined reference to 'ext4_fs_put_inode_ref'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext_dev.o): in function 'extdev_dirclose':
H:/libusbhsfs/source/lwext4/ext_dev.c:565: undefined reference to 'ext4_dir_close'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext_dev.o): in function 'extdev_dirnext':
H:/libusbhsfs/source/lwext4/ext_dev.c:516: undefined reference to 'ext4_dir_entry_next'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: H:/libusbhsfs/source/lwext4/ext_dev.c:532: undefined reference to 'ext4_fs_get_inode_ref'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: H:/libusbhsfs/source/lwext4/ext_dev.c:539: undefined reference to 'ext4_fs_put_inode_ref'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext_dev.o): in function 'extdev_dirreset':
H:/libusbhsfs/source/lwext4/ext_dev.c:489: undefined reference to 'ext4_dir_entry_rewind'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext_dev.o): in function 'extdev_diropen':
H:/libusbhsfs/source/lwext4/ext_dev.c:465: undefined reference to 'ext4_dir_open'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext_dev.o): in function 'extdev_mkdir':
H:/libusbhsfs/source/lwext4/ext_dev.c:435: undefined reference to 'ext4_dir_mk'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext_dev.o): in function 'extdev_rename':
H:/libusbhsfs/source/lwext4/ext_dev.c:412: undefined reference to 'ext4_frename'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext_dev.o): in function 'extdev_chdir':
H:/libusbhsfs/source/lwext4/ext_dev.c:373: undefined reference to 'ext4_dir_open'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: H:/libusbhsfs/source/lwext4/ext_dev.c:377: undefined reference to 'ext4_dir_close'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext_dev.o): in function 'extdev_unlink':
H:/libusbhsfs/source/lwext4/ext_dev.c:350: undefined reference to 'ext4_fremove'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext_dev.o): in function 'extdev_link':
H:/libusbhsfs/source/lwext4/ext_dev.c:329: undefined reference to 'ext4_flink'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext_dev.o): in function 'extdev_stat':
H:/libusbhsfs/source/lwext4/ext_dev.c:303: undefined reference to 'ext4_raw_inode_fill'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext_dev.o): in function 'extdev_seek':
H:/libusbhsfs/source/lwext4/ext_dev.c:244: undefined reference to 'ext4_fseek'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: H:/libusbhsfs/source/lwext4/ext_dev.c:248: undefined reference to 'ext4_ftell'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext_dev.o): in function 'extdev_read':
H:/libusbhsfs/source/lwext4/ext_dev.c:221: undefined reference to 'ext4_fread'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext_dev.o): in function 'extdev_write':
H:/libusbhsfs/source/lwext4/ext_dev.c:188: undefined reference to 'ext4_ftell'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: H:/libusbhsfs/source/lwext4/ext_dev.c:188: undefined reference to 'ext4_fsize'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: H:/libusbhsfs/source/lwext4/ext_dev.c:191: undefined reference to 'ext4_fseek'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: H:/libusbhsfs/source/lwext4/ext_dev.c:198: undefined reference to 'ext4_fwrite'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext_dev.o): in function 'extdev_close':
H:/libusbhsfs/source/lwext4/ext_dev.c:164: undefined reference to 'ext4_fclose'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext_dev.o): in function 'extdev_open':
H:/libusbhsfs/source/lwext4/ext_dev.c:142: undefined reference to 'ext4_fopen2'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext_dev.o): in function 'extdev_fchmod':
H:/libusbhsfs/source/lwext4/ext_dev.c:696: undefined reference to 'ext4_fs_get_inode_ref'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: H:/libusbhsfs/source/lwext4/ext_dev.c:706: undefined reference to 'ext4_inode_get_mode'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: H:/libusbhsfs/source/lwext4/ext_dev.c:709: undefined reference to 'ext4_inode_set_mode'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: H:/libusbhsfs/source/lwext4/ext_dev.c:713: undefined reference to 'ext4_fs_put_inode_ref'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext_dev.o): in function 'ext_trans_stop':
H:/libusbhsfs/source/lwext4/ext_dev.c:891: undefined reference to 'jbd_journal_commit_trans'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext_dev.o): in function 'ext_trans_abort':
H:/libusbhsfs/source/lwext4/ext_dev.c:907: undefined reference to 'jbd_journal_free_trans'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext_dev.o): in function 'ext_trans_start':
H:/libusbhsfs/source/lwext4/ext_dev.c:867: undefined reference to 'jbd_journal_new_trans'
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/10.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/portlibs/switch/lib\libusbhsfs.a(ext_dev.o): in function 'ext_trans_abort':
H:/libusbhsfs/source/lwext4/ext_dev.c:907: undefined reference to 'jbd_journal_free_trans'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [/opt/devkitpro/libnx/switch_rules:80: /h/tinleaf/tinleaf.elf] Error 1
make: *** [Makefile:170: build] Error 2`

I tried googling but couldn't find a fix.
I am using Windows 10, devkitpro is setup and running, with all switch-libs installed. I also setup and installed libusbhsfs GPL.

Any fix for this issue?

**Comment by CaiMiao** [comment]
I made it build with below steps:
1. Build libusbhsfs once in ISC
2. ~~Build tinleaf once~~
3. Build libusbhsfs again in GPL
4. Build tinleaf

see if it works
