### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by yyoossk** [blawar/tinleaf#3]
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/9.2.0/../../../../aarch64-none-elf/bin/ld.exe: cannot find -lssh2

how to get -lssh2?

**Comment by pixeltester** [comment]
Simple fix: https://github.com/blawar/tinleaf/pull/4

**Comment by blawar** [comment]
just remove -lssh2 from the makefile, that is specific to my custom environment.
